<?php

/**
 * Implements hook_preprocess_media().
 */
function sitestudio_lazyload_youtube_preprocess_media(&$variables) {
  if (!isset($variables['elements']['#media'])) {
    return;
  }

  /** @var \Drupal\media\Entity\Media $media */
  $media = $variables['elements']['#media'];
  if ($media->bundle() == 'youtube_video') {
    if (isset($variables['content']['field_media_oembed_video_1'][0]['#placeholder']['#thumbnail'])) {
      if ($media->field_thumbnail->entity) {
        $uri = $media->field_thumbnail->entity->getFileUri();
        $url = \Drupal::service('file_url_generator')->generateAbsoluteString($uri);
        $variables['content']['field_media_oembed_video_1'][0]['#placeholder']['#thumbnail'] = $url;
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function ss_lazyload_youtube_theme() {
    return [
      'oembed_lazyload_placeholder__youtube' => [
        'template' => 'oembed-lazyload-placeholder--youtube',
        'base hook' => 'oembed_lazyload_placeholder',
      ],
    ];
  }
  
